/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SET_SEARCH_STRINGS = 'SET_SEARCH_STRINGS';
export const SET_BASIC_INFO = 'SET_BASIC_INFO';
export const MODIFY_FAVORITE = 'MODIFY_FAVORITE';
export const FETCH_RECOMMENDATIONS_SUCCEEDED = 'FETCH_RECOMMENDATIONS_SUCCEEDED';
export const FETCH_RECOMMENDATIONS_FAILED = 'FETCH_RECOMMENDATIONS_FAILED';
